let a = 'a';
let b = 'b';
let c = 'c';
let d = 'd';
let e = 'e';
let f = 'f';
let g = 'g';
let h = 'h';
let i = 'i';
let j = 'j';
let k = 'k';
let l = 'l';
let m = 'm';
let n = 'n';
let o = 'o';
let p = 'p';
let q = 'q';
let r = 'r';
let s = 's';
let t = 't';
let u = 'u';
let v = 'v';
let w = 'w';
let x = 'x';
let y = 'y';
let z = 'z';
let æ = 'æ';
let ø = 'ø';
let å = 'å';

const tasks = [
  {
    time: 180,
    introNb:
      'Hei! Endelig skal jeg få oppfylt drømmen min om å hoppe i fallskjerm. For at jeg skal lande, trenger jeg hjelp fra deg og tastaturet. Du skal legge venstre pekefinger på f. Du skal legge høyre pekefinger på j. Kan du kjenne at tastene har et merke? Trykk start, så begynner vi.',
    introNn:
      'Hei! Endeleg skal eg få oppfylt draumen min om å hoppe i fallskjerm. For at eg skal lande, treng eg hjelp frå deg og tastaturet. Du skal legge venstre peikefinger på f. Du skal legge høgre peikefinger på j. Kan du kjenne at tastane har eit merke? Trykk på start, så startar vi.',
    successNb:
      'Hurra! Dette klarte vi fint. Fallskjermhopping var utrolig gøy.',
    successNn:
      'Hurra! Dette klarte du fint. Fallskjermhopping var utruleg kjekt.',
    failureNb: 'Dette skal vi klare. Prøv en gang til.',
    failureNn: 'Dette skal vi klare. Prøv ein gong til.',
    task: [
      'test ',
      f,
      f,
      f,
      f,
      f,
      f,
      f,
      f,
      j,
      j,
      j,
      j,
      j,
      j,
      j,
      j,
      f,
      f,
      f,
      f,
      f,
      f,
      j,
      j,
      j,
      j,
      j,
      j,
      f,
      f,
      f,
      j,
      j,
      j,
      f,
      f,
      j,
      j,
      f,
      f,
      f,
      f,
      j,
      j,
      j,
      j,
      f,
      f,
      f,
      j,
      j,
      j,
      f,
      f,
      j,
      j,
      j,
      j,
      f,
      f,
      f,
      f,
      f,
      f,
      f,
      f,
      j,
      j,
      j,
      f,
      j,
      j,
      j,
      j,
      j,
      j,
      j,
      j,
      f,
      f,
      f,
      f,
      j,
      f,
      f,
      f,
      f,
      f,
      f,
      j,
      j,
      j,
      j,
      f,
      f,
      j,
      f,
      f,
      f,
      j,
      j,
      f,
      f,
      f,
      j,
      j,
      j,
      f,
      j,
      j,
      j,
      j,
      f,
      f,
      j,
      j,
      j,
      j,
      f,
      f,
      f,
      f,
      f,
      f,
      f,
      j,
      f,
      f,
      j,
      j,
      f,
      f,
      f,
      f,
      j,
      j,
      j,
      j,
      f,
      f,
      f,
      f,
      f,
      f,
      f,
      f,
      f,
      j,
      j,
      j,
      j,
      j,
      j,
      j,
      j,
      j,
      f,
      f,
      f,
      j,
      j,
      j,
      f,
      j,
      f,
      f,
      j,
      j,
      f,
    ],
    startPosition: [0, -25],
    animation: [
      [70, 40],
      [0, 0],
      [70, 40],
    ],
  },
  {
    time: 180,
    introNb:
      'Vet du hva? Jeg tror det finnes en skatt på havbunnen. Bli med i dykkerklokken min, så kan vi lete sammen. Du må legge pekefingrene på f og j. Kjenner du merket? De nye bokstavene er d og k. Du må legge venstre langfinger på d. Du må legge høyre langfinger på k. Trykk på start når du er klar.',
    introNn:
      'Veit du kva? Eg trur det finst ein skatt på havbotnen. Bli med i dykkarklokka mi, så kan vi leite saman. Du må legge peikefingrane på f og j. Kjenner du merket? Dei nye bokstavane er d og k. Du må legge venstre langfinger på d. Du må legge høgre langfinger på k. Trykk på start når du er klar.',
    successNb: 'Ja! Vi klarte det. Skatten er vår!',
    successNn: 'Ja! Vi klarte det. Skatten er vår!',
    failureNb:
      'Åh, så du skatten? Prøv en gang til, så klarer vi å få tak i den.',
    failureNn:
      'Åh, såg du skatten? Prøv ein gong til, så klarer vi å få tak i han.',
    task: [
      d,
      d,
      d,
      d,
      d,
      d,
      d,
      d,
      k,
      k,
      k,
      k,
      k,
      k,
      k,
      k,
      d,
      d,
      d,
      d,
      d,
      d,
      k,
      k,
      k,
      k,
      k,
      k,
      d,
      d,
      d,
      d,
      k,
      k,
      k,
      k,
      d,
      d,
      k,
      k,
      k,
      d,
      d,
      d,
      d,
      d,
      d,
      k,
      k,
      k,
      k,
      k,
      k,
      d,
      d,
      k,
      k,
      k,
      d,
      d,
      f,
      f,
      d,
      d,
      f,
      f,
      k,
      k,
      j,
      j,
      k,
      k,
      j,
      j,
      f,
      f,
      d,
      f,
      d,
      d,
      k,
      k,
      k,
      j,
      k,
      j,
      k,
      f,
      f,
      f,
      d,
      d,
      d,
      f,
      f,
      f,
      d,
      d,
      d,
      f,
      j,
      j,
      k,
      k,
      k,
      j,
      j,
      k,
      k,
      k,
      j,
      k,
      j,
      k,
      f,
      f,
      j,
      j,
      d,
      d,
      k,
      k,
      f,
      k,
      j,
      d,
      k,
      d,
      f,
      k,
      j,
      f,
      f,
      k,
      k,
      d,
      d,
      k,
      k,
      f,
      d,
      f,
      f,
      j,
      k,
      j,
      j,
      d,
      d,
      k,
      k,
      f,
      j,
      j,
      k,
      k,
      d,
      f,
      j,
    ],
    startPosition: [0, -25],
    animation: [
      [70, 40],
      [0, 0],
      [70, 40],
    ],
  },
  {
    time: 180,
    introNb:
      'De som klarer å balansere på en line må være superhelter. Jeg har lyst til å være en superhelt. For at jeg skal komme meg over linen må du trykke s og l, og de andre bokstavene som du har øvd på. Du må legge venstre ringfinger på s. Du må legge høyre ringfinger på l. Er du klar? Trykk på start. ',
    introNn:
      'Dei som klarer å balansere på ei line må vere superheltar. Eg har lyst til å vere ein superhelt. For at eg skal kome meg over lina må du trykke s og l, og dei andre bokstavane som du har øvd på. Du må legge venstre ringfinger på s. Du må legge høgre ringfinger på l. Er du klar? Trykk på start. ',
    successNb: 'Hurra! Jeg er en superhelt.',
    successNn: 'Hurra! Eg er ein superhelt.',
    failureNb: 'Oi, det var vanskelig å gå på line. La oss starte på nytt. ',
    failureNn: 'Oi, det var vanskeleg å gå på line. La oss starte på nytt. ',
    task: [
      l,
      l,
      l,
      l,
      l,
      s,
      s,
      s,
      l,
      l,
      l,
      s,
      s,
      s,
      s,
      s,
      s,
      s,
      s,
      s,
      l,
      l,
      l,
      l,
      l,
      l,
      l,
      l,
      s,
      s,
      s,
      s,
      s,
      s,
      l,
      l,
      s,
      s,
      s,
      l,
      l,
      k,
      s,
      s,
      l,
      l,
      l,
      s,
      s,
      s,
      s,
      f,
      f,
      k,
      j,
      j,
      k,
      l,
      l,
      l,
      l,
      f,
      f,
      f,
      s,
      s,
      j,
      l,
      l,
      k,
      j,
      d,
      s,
      d,
      s,
      s,
      l,
      l,
      d,
      d,
      s,
      s,
      f,
      k,
      k,
      k,
      j,
      j,
      j,
      k,
      l,
      k,
      j,
      k,
      k,
      j,
      j,
      f,
      f,
      s,
      s,
      s,
      j,
      k,
      j,
      s,
      s,
      s,
      l,
      l,
      l,
      k,
      k,
      j,
      k,
      j,
      j,
      d,
      d,
      s,
      f,
      s,
      f,
      d,
      s,
      f,
      d,
      j,
      d,
      j,
      s,
      k,
      f,
      j,
      f,
      l,
      l,
      l,
      d,
      d,
      s,
      s,
      s,
    ],
    startPosition: [0, -25],
    animation: [
      [70, 40],
      [0, 0],
      [70, 40],
    ],
  },
  {
    time: 180,
    introNb:
      'Jippi, det er snø! I dag vil jeg ake superfort. Kan du og tastaturet hjelpe meg? De nye bokstavene er a, ø og æ.  Du må legge venstre lillefinger på a. Du må legge høyre lillefinger på ø. Du må flytte høyre lillefinger for å trykke æ. Nå skal du også skrive ord. Mellom ordene skal det være mellomrom. Du skal trykke mellomromstasten med tomlene. Legg fingrene klare på tastaturet. Trykk på start når du er klar.',
    introNn:
      'Jippi, det er snø! I dag vil eg ake superfort. Kan du og tastaturet hjelpe meg? Dei nye bokstavane er a, ø og æ.  Du må legge venstre veslefinger på a. Du må legge høgre veslefinger på ø.  Du må flytte høgre veslefinger for å trykke æ. No skal du også skrive ord. Mellom orda skal det vere mellomrom. Du skal trykke mellomromstasten med tomlane. Legg fingrane klare på tastaturet. Trykk på start når du er klar.',
    successNb: 'Det var kjempegøy!',
    successNn: 'Det var kjempegøy!',
    failureNb:
      'Vi må ha større fart, så vi kommer helt ned bakken. Prøv igjen!',
    failureNn: 'Vi må ha større fart, så vi kjem heilt ned bakken. Prøv igjen!',
    task: [
      a,
      a,
      a,
      a,
      a,
      a,
      a,
      a,
      ø,
      ø,
      ø,
      ø,
      ø,
      ø,
      ø,
      a,
      a,
      æ,
      æ,
      æ,
      æ,
      æ,
      æ,
      a,
      a,
      a,
      a,
      a,
      a,
      ø,
      ø,
      ø,
      ø,
      ø,
      a,
      a,
      a,
      a,
      æ,
      æ,
      æ,
      æ,
      æ,
      a,
      a,
      a,
      a,
      ø,
      ø,
      ø,
      ø,
      a,
      a,
      a,
      a,
      æ,
      æ,
      æ,
      æ,
      a,
      a,
      ø,
      ø,
      æ,
      æ,
      a,
      a,
      a,
      s,
      s,
      s,
      ø,
      ø,
      ø,
      æ,
      æ,
      æ,
      l,
      l,
      l,
      a,
      a,
      s,
      s,
      d,
      d,
      a,
      a,
      s,
      s,
      d,
      d,
      a,
      a,
      ø,
      ø,
      l,
      l,
      ø,
      ø,
      l,
      l,
      æ,
      æ,
      l,
      l,
      æ,
      æ,
      f,
      f,
      a,
      a,
      j,
      j,
      k,
      k,
      j,
      ø,
      æ,
      d,
      d,
      d,
      j,
      j,
      j,
      a,
      a,
      æ,
      j,
      j,
      j,
      k,
      l,
      l,
      a,
      k,
      s,
      j,
      f,
      l,
      l,
      s,
      a,
      'sa ',
      s,
      a,
      l,
      'sal ',
      s,
      a,
      k,
      'sak',
      k,
      l,
      ø,
      'klø',
      j,
      a,
      'ja',
    ],
    startPosition: [0, -25],
    animation: [
      [70, 40],
      [0, 0],
      [70, 40],
    ],
  },
  {
    time: 180,
    introNb:
      'Kom skal du få treffe vennen min Tastaturid.  Jeg vil ri på hesten min til Tastaturid. For å hjelpe meg dit må du trykke g og h . Du må bruke venstre pekefinger på g. Du må bruke høyre pekefinger på h.  Husk å ha fingrene på ledetastene. Trykk på start og hoppla så rir vi til Tastaturid.',
    introNn:
      'Kom skal du få treffe vennen min Tastaturid.  Eg vil ri på hesten min til Tastaturid. For å hjelpe meg dit må du trykke g og h. Du må bruke venstre peikefinger på g. Du må bruke høgre peikefinger på h.  Hugs å ha fingrane på leietastane. Trykk på start og hoppla så rir vi til Tastaturid.',
    successNb: 'Endelig framme hos Tastaturid. Dette klarte vi fint.',
    successNn: 'Endeleg framme hos Tastaturid. Dette klarte vi fint.',
    failureNb: 'Det var vanskelig å ri. Prøv igjen.',
    failureNn: 'Det var vanskeleg å ri. Prøv igjen.',
    task: [
      h,
      h,
      h,
      g,
      g,
      g,
      g,
      h,
      h,
      h,
      h,
      h,
      g,
      g,
      h,
      h,
      h,
      g,
      g,
      g,
      h,
      g,
      h,
      h,
      g,
      g,
      g,
      h,
      l,
      f,
      f,
      j,
      j,
      h,
      j,
      h,
      f,
      d,
      s,
      d,
      g,
      g,
      h,
      j,
      h,
      j,
      k,
      ø,
      a,
      g,
      g,
      f,
      d,
      s,
      h,
      h,
      æ,
      k,
      g,
      s,
      j,
      l,
      l,
      l,
      f,
      h,
      g,
      k,
      k,
      a,
      a,
      ø,
      j,
      j,
      s,
      a,
      g,
      'sag',
      j,
      a,
      g,
      'jag',
      f,
      a,
      g,
      'fag',
      s,
      a,
      s,
      a,
      'sa',
      h,
      h,
      'ha',
      d,
      a,
      d,
      a,
      g,
      'dag',
      g,
      a,
      'gal',
    ],
    startPosition: [0, -25],
    animation: [
      [70, 40],
      [0, 0],
      [70, 40],
    ],
  },
  {
    time: 180,
    introNb:
      'Jeg er råsterk! Kom å bli med på tautrekking mot Tastaturid. Du og tastaturet må være på mitt lag. De nye bokstavene er t og y.  Du må  flytte venstre pekefinger opp til t. Du må flytte høyre pekefinger opp til y. Legg fingrene klare på ledetastene. Klar, ferdig, gå!',
    introNn:
      'Eg er råsterk! Kom å bli med på tautrekking mot Tastaturid. Du og tastaturet må vere på mitt lag. Dei nye bokstavane er t og y.  Du må  flytte venstre peikefinger opp til t. Du må flytte høgre peikefinger opp til y. Legg fingrane klare på leietastane. Klar, ferdig, gå!',
    successNb: 'Hurra, vi vant!',
    successNn: 'Hurra, vi vann!',
    failureNb: 'Dette skal vi klare, prøv en gang til.',
    failureNn: 'Dette skal vi klare, prøv ein gong til.',
    task: [
      y,
      y,
      y,
      y,
      y,
      y,
      y,
      y,
      t,
      t,
      t,
      t,
      t,
      t,
      y,
      y,
      y,
      t,
      t,
      t,
      t,
      y,
      y,
      y,
      t,
      t,
      t,
      y,
      y,
      t,
      t,
      y,
      y,
      j,
      j,
      f,
      f,
      t,
      t,
      f,
      f,
      t,
      t,
      j,
      y,
      d,
      d,
      f,
      t,
      j,
      j,
      y,
      h,
      y,
      y,
      a,
      s,
      d,
      f,
      g,
      t,
      t,
      æ,
      ø,
      l,
      k,
      j,
      h,
      y,
      a,
      a,
      t,
      t,
      ø,
      ø,
      æ,
      æ,
      y,
      y,
      g,
      t,
      f,
      g,
      t,
      y,
      y,
      y,
      h,
      j,
      y,
      j,
      a,
      k,
      f,
      l,
      s,
      ø,
      k,
      t,
      s,
      a,
      h,
      y,
      l,
      'hyl',
      t,
      a,
      'ta',
      t,
      a,
      k,
      'tak',
      d,
      a,
      t,
      a,
      'data',
      g,
      ø,
      y,
      'gøy',
      s,
      ø,
      t,
      'søt',
    ],
    startPosition: [0, -25],
    animation: [
      [70, 40],
      [0, 0],
      [70, 40],
    ],
  },
  {
    time: 180,
    introNb:
      'Tastaturid har mistet nøkkelen til huset sitt. Jeg må kjøre til Tastaturid med en reservenøkkel. Du må hjelpe meg å kjøre. Du skal taste de nye bokstavene b og n. Husk å plassere fingrene på ledetastene. Du må flytte venstre pekefinger ned til b. Du må flytte høyre pekefinger ned til n. La oss skynde oss til Tastaturid. ',
    introNn:
      'Tastaturid har mista nøkkelen til huset sitt. Eg må køyre til Tastaturid med ein reservenøkkel. Du må hjelpe meg å køyre. Du skal taste dei nye bokstavane b og n. Hugs å plassere fingrane på leietastane. Du må flytte venstre peikefinger ned til b. Du må flytte høgre peikefinger ned til n. La oss skunde oss til Tastaturid. ',
    successNb: 'Værsågod Tastaturid. Her er nøkkelen din.',
    successNn: 'Værsågod Tastaturid. Her er nøkkelen din.',
    failureNb: 'Prøv en gang til.',
    failureNn: 'Prøv ein gong til.',
    task: [
      b,
      b,
      b,
      b,
      b,
      n,
      n,
      n,
      n,
      n,
      b,
      b,
      b,
      n,
      n,
      n,
      n,
      b,
      b,
      b,
      b,
      n,
      n,
      n,
      b,
      b,
      b,
      n,
      n,
      b,
      n,
      b,
      b,
      n,
      n,
      h,
      f,
      f,
      g,
      g,
      b,
      a,
      j,
      j,
      n,
      j,
      y,
      y,
      h,
      t,
      g,
      b,
      b,
      g,
      b,
      n,
      n,
      ø,
      n,
      l,
      k,
      k,
      n,
      n,
      b,
      a,
      a,
      s,
      d,
      d,
      f,
      t,
      t,
      g,
      l,
      f,
      k,
      k,
      d,
      æ,
      t,
      n,
      n,
      y,
      'ny',
      b,
      b,
      y,
      'by',
      n,
      a,
      t,
      t,
      'natt',
      s,
      y,
      n,
      'syn',
      b,
      ø,
      'bø',
      b,
      æ,
      'bæ',
      b,
      a,
      l,
      l,
      'ball',
      b,
      a,
      d,
      'bad',
      b,
      a,
      k,
      'bak',
    ],
    startPosition: [0, -25],
    animation: [
      [70, 40],
      [0, 0],
      [70, 40],
    ],
  },
  {
    time: 180,
    introNb:
      'Hei på deg, nå er vi i verdensrommet. Kan du hjelpe meg å fly UFO? Vi skal fly til den grønne planeten. De nye bokstavene som kan hjelpe oss med å klare oppdraget er r og u. Legg fingrene på ledetastene. Du må flytte venstre pekefinger opp til r. Du må flytte høyre pekefinger opp til u. Husk å bruke riktig finger på alle tastene! Trykk start, så drar vi!',
    introNn:
      'Hei på deg, no er vi i verdsrommet. Kan du hjelpe meg å fly UFO? Vi skal fly til den grøne planeten. Dei nye bokstavane som kan hjelpe oss med å klare oppdraget er r og u. Legg fingrane på leietastane. Du må flytte venstre peikefinger opp til r. Du må flytte høgre peikefinger opp til u. Hugs å bruke riktig finger på alle tastane! Trykk start, så dreg vi!',
    successNb:
      'Ja, vi klarte det. Det blir spennende å utforske denne planeten.',
    successNn:
      'Ja, vi klarte det. Det blir spennande å utforske denne planeten.',
    failureNb: 'Prøv en gang til.',
    failureNn: 'Prøv ein gong til.',
    task: [
      r,
      r,
      r,
      r,
      r,
      r,
      r,
      u,
      u,
      u,
      u,
      r,
      r,
      r,
      r,
      u,
      u,
      u,
      r,
      r,
      r,
      r,
      r,
      u,
      u,
      y,
      j,
      r,
      r,
      r,
      u,
      u,
      f,
      f,
      r,
      r,
      f,
      j,
      j,
      u,
      u,
      j,
      n,
      n,
      d,
      d,
      r,
      r,
      f,
      b,
      l,
      l,
      j,
      j,
      u,
      j,
      a,
      s,
      s,
      d,
      f,
      r,
      t,
      f,
      b,
      æ,
      ø,
      l,
      k,
      j,
      u,
      j,
      n,
      d,
      g,
      g,
      t,
      r,
      r,
      k,
      u,
      u,
      y,
      y,
      u,
      r,
      t,
      r,
      g,
      f,
      u,
      u,
      j,
      n,
      n,
      r,
      u,
      t,
      u,
      r,
      'tur',
      k,
      u,
      l,
      'kul',
      b,
      r,
      a,
      'bra',
      h,
      u,
      s,
      'hus',
      'hud',
      'bra',
      'rar',
    ],
    startPosition: [0, -25],
    animation: [
      [70, 40],
      [0, 0],
      [70, 40],
    ],
  },
  {
    time: 180,
    introNb:
      'Jeg er klar for å løpe langt. Maraton er 42 kilometer. Jeg har lyst til å vinne en medalje. V og m er de nye bokstavene som skal hjelpe oss. Legg fingrene på ledetastene. Du må flytte venstre pekefinger ned til v. Du må flytte høyre pekefinger ned til m. Jeg står klar på startstreken. Klar-ferdig-gå!',
    introNn:
      'Eg er klar for å springe langt. Maraton er 42 kilometer. Eg har lyst til å vinne ein medalje. V og m er dei nye bokstavane som skal hjelpe oss. Legg fingrane på leietastane. Du må flytte venstre peikefinger ned til v. Du må flytte høgre peikefinger ned til m. Eg står klar på startstreken. Klar-ferdig-gå!',
    successNb: 'Hurra! Medaljen er i boks.',
    successNn: 'Hurra! Medaljen er i boks.',
    failureNb: 'Vi prøver en gang til.',
    failureNn: 'Prøv ein gong til.',
    task: [
      v,
      v,
      v,
      v,
      v,
      v,
      m,
      m,
      m,
      m,
      m,
      v,
      v,
      v,
      v,
      m,
      m,
      m,
      m,
      m,
      m,
      v,
      v,
      v,
      v,
      m,
      m,
      m,
      v,
      v,
      m,
      v,
      m,
      b,
      j,
      m,
      j,
      m,
      m,
      v,
      f,
      g,
      g,
      d,
      s,
      s,
      a,
      a,
      a,
      u,
      y,
      u,
      t,
      t,
      r,
      v,
      v,
      v,
      y,
      m,
      h,
      h,
      l,
      l,
      ø,
      n,
      n,
      m,
      r,
      r,
      g,
      b,
      b,
      b,
      v,
      d,
      d,
      m,
      v,
      m,
      v,
      u,
      æ,
      r,
      b,
      l,
      k,
      m,
      d,
      d,
      a,
      a,
      v,
      u,
      u,
      n,
      n,
      æ,
      æ,
      j,
      j,
      h,
      j,
      g,
      g,
      b,
      f,
      f,
      r,
      v,
      v,
      a,
      m,
      a,
      t,
      'mat',
      m,
      ø,
      'mø',
      v,
      a,
      r,
      m,
      'varm',
      a,
      r,
      m,
      'arm',
      m,
      u,
      s,
      'mus',
      t,
      u,
      n,
      'tun',
      d,
      u,
      n,
      'dun',
    ],
    startPosition: [0, -25],
    animation: [
      [70, 40],
      [0, 0],
      [70, 40],
    ],
  },
  {
    time: 180,
    introNb:
      'Mmmm, jeg elsker eplekake. Tastaturid har lovet å bake eplekake. Jeg må plukke hele kurven full for å ha nok epler til en kake. Men jeg trenger din hjelp. De nye bokstavene er e og i.  Legg fingrene på ledetastene. Du må flytte venstre langfinger opp til "E". Du må flytte høyre langfinger opp til "I". Kom igjen, så setter vi i gang!',
    introNn:
      'Mmmm, eg elskar eplekake. Tastaturid har lova å bake eplekake. Eg må plukke heile korga full for å ha nok eple til ei kake. Men eg treng di hjelp. Dei nye bokstavane er e og i.  Legg fingrane på leietastane. Du må flytte venstre langfinger opp til e. Du må flytte høgre langfinger opp til i. Kom igjen, så set vi i gong! ',
    successNb: 'Å, nå gleder jeg meg til å spise eplekake!',
    successNn: 'Å, no gler eg meg til å ete eplekake!',
    failureNb: 'Vi mangler noen epler. Prøv en gang til.',
    failureNn: 'Vi manglar nokre eple. Prøv ein gong til.',
    task: [
      e,
      e,
      e,
      e,
      e,
      e,
      i,
      i,
      i,
      i,
      i,
      i,
      i,
      i,
      e,
      e,
      e,
      i,
      i,
      i,
      f,
      e,
      f,
      e,
      i,
      j,
      i,
      j,
      i,
      v,
      f,
      e,
      v,
      f,
      e,
      e,
      n,
      j,
      i,
      i,
      n,
      j,
      i,
      i,
      e,
      e,
      a,
      a,
      d,
      d,
      e,
      e,
      i,
      i,
      k,
      k,
      i,
      i,
      k,
      k,
      s,
      a,
      f,
      e,
      ø,
      æ,
      æ,
      k,
      k,
      i,
      i,
      e,
      e,
      d,
      d,
      e,
      e,
      i,
      i,
      h,
      h,
      j,
      y,
      y,
      i,
      i,
      v,
      b,
      f,
      e,
      d,
      m,
      n,
      j,
      i,
      g,
      r,
      r,
      t,
      t,
      e,
      e,
      f,
      j,
      j,
      h,
      u,
      i,
      i,
      k,
      s,
      s,
      a,
      a,
      e,
      e,
      d,
      v,
      l,
      l,
      æ,
      æ,
      i,
      i,
      m,
      m,
      i,
      n,
      'min',
      d,
      i,
      n,
      'din',
      d,
      e,
      t,
      'det',
      r,
      i,
      k,
      'rik',
      l,
      e,
      'le',
      v,
      i,
      'vi',
      'vit',
      s,
      e,
      l,
      'sel',
    ],
    startPosition: [0, -25],
    animation: [
      [70, 40],
      [0, 0],
      [70, 40],
    ],
  },
  {
    time: 180,
    introNb:
      'Å, så herlig det er med ferie. Her på cruiseskipet slapper jeg skikkelig av. I dag skal vi på utflukt til en tropisk øy. De nye tastene som hjelper oss å styre skipet mot øyen er c og komma. Du må flytte  venstre langfinger ned til c. Du må flytte høyre langfinger ned til komma. Ship O hoi, her kommer vi. ',
    introNn:
      'Å, så herleg det er med ferie. Her på cruiseskipet slappar eg skikkeleg av. I dag skal vi på ei utflukt til ei tropisk øy. Dei nye tastane som hjelper oss å styre skipet mot øya er c og komma. Du må flytte  venstre langfinger ned til c. Du må flytte høgre langfinger ned til komma. Ship O hoi, her kjem vi.',
    successNb: 'Dette gikk fint. Det skal bli godt å være på en tropisk øy.',
    successNn: 'Dette gjekk fint. Det skal bli godt å vere på ei tropisk øy.',
    failureNb: 'La oss prøve en gang til. Den tropiske øyen er i sikte.',
    failureNn: 'La oss prøve ein gong til. Den tropiske øya er i sikte.',
    task: [
      'comma',
      'comma',
      'comma',
      'comma',
      'comma',
      'comma',
      'comma',
      'comma',
      c,
      c,
      c,
      c,
      'comma',
      'comma',
      'comma',
      'comma',
      c,
      c,
      c,
      'comma',
      'comma',
      'comma',
      'comma',
      c,
      c,
      c,
      c,
      c,
      'comma',
      'comma',
      c,
      c,
      'comma',
      'comma',
      c,
      c,
      'comma',
      c,
      'comma',
      c,
      v,
      v,
      b,
      v,
      c,
      c,
      m,
      m,
      b,
      h,
      h,
      y,
      n,
      c,
      c,
      f,
      f,
      r,
      r,
      e,
      s,
      s,
      ø,
      ø,
      i,
      i,
      i,
      n,
      n,
      j,
      k,
      'comma',
      'comma',
      a,
      a,
      f,
      c,
      d,
      e,
      y,
      g,
      g,
      c,
      u,
      i,
      k,
      k,
      m,
      m,
      j,
      j,
      j,
      h,
      r,
      r,
      r,
      d,
      v,
      t,
      m,
      e,
      æ,
      e,
      'comma',
      c,
      d,
      'cd',
      v,
      i,
      l,
      'vil',
      s,
      i,
      d,
      e,
      'side',
      m,
      i,
      l,
      'mil',
      v,
      e,
      v,
      'vev',
      v,
      e,
      v,
      e,
    ],
    startPosition: [0, -25],
    animation: [
      [70, 40],
      [0, 0],
      [70, 40],
    ],
  },
  {
    time: 180,
    introNb:
      'Det er på tide å trene litt igjen. Denne gangen skal jeg løpe orienteringsløp. For å klare oppdraget må jeg samle 10 poster. Kan du hjelpe meg å løpe? De nye bokstavene er w og o. Du må flytte venstre ringfinger opp til w. Du må flytte høyre ringfinger opp til o. Klar-ferdig-gå.',
    introNn:
      'Det er på tide å trene litt igjen. Denne gongen skal eg springe orienteringsløp. For å klare oppdraget må eg samle 10 poster. Kan du hjelpe meg å springe? Dei nye bokstavane er w og o. Du må flytte venstre ringfinger opp til w. Du må flytte høgre ringfinger opp til o. Klar- ferdig-gå.',
    successNb: 'Vi klarte 10 poster! Takk for hjelpen!',
    successNn: 'Vi klarte 10 poster! Takk for hjelpa!',
    failureNb: 'Vi må springe litt fortere. Kom så prøver vi en gang til.',
    failureNn: 'Vi må springe litt fortare. Kom så prøver vi ein gong til.',
    task: [
      o,
      o,
      o,
      o,
      o,
      w,
      w,
      w,
      w,
      o,
      o,
      o,
      l,
      o,
      o,
      w,
      w,
      w,
      s,
      w,
      w,
      s,
      l,
      l,
      o,
      o,
      l,
      k,
      'comma',
      'comma',
      w,
      w,
      s,
      w,
      w,
      s,
      d,
      ø,
      ø,
      o,
      o,
      o,
      l,
      a,
      s,
      w,
      w,
      f,
      f,
      j,
      j,
      y,
      y,
      j,
      æ,
      æ,
      k,
      o,
      l,
      w,
      w,
      t,
      t,
      f,
      w,
      o,
      o,
      u,
      u,
      b,
      b,
      b,
      o,
      e,
      e,
      w,
      f,
      w,
      w,
      s,
      s,
      y,
      u,
      i,
      o,
      h,
      h,
      j,
      j,
      j,
      v,
      f,
      r,
      r,
      r,
      w,
      e,
      w,
      n,
      n,
      o,
      o,
      c,
      f,
      f,
      v,
      a,
      w,
      h,
      m,
      m,
      j,
      w,
      w,
      g,
      g,
      o,
      s,
      o,
      l,
      'sol',
      l,
      e,
      s,
      e,
      'lese',
      ø,
      r,
      n,
      'ørn',
      k,
      i,
      w,
      i,
      'kiwi',
      n,
      e,
      i,
      'nei',
      'bok',
      'stol',
      o,
      o,
      o,
    ],
    startPosition: [0, -25],
    animation: [
      [70, 40],
      [0, 0],
      [70, 40],
    ],
  },
  {
    time: 180,
    introNb:
      'Endelig har jeg lært å slå hjul. Skal jeg vise deg? Jeg kan slå hjul over hele hagen. Men jeg trenger hjelp av deg og tastene. De nye tastene er x og punktum. Du må flytte venstre ringfinger  ned til x. Du må flytte høyre ringfinger ned til punktum. Trykk på start og vi er i gang.',
    introNn:
      'Endeleg har eg lært meg å slå hjul. Skal eg vise deg? Eg kan slå hjul over heile hagen. Men eg treng hjelp av deg og tastane. Dei nye tastane er x og punktum. Du må flytte venstre ringfinger ned til x. Du må flytte høgre ringfinger ned til punktum. Trykk på start og vi er i gong.',
    successNb:
      'Dette gikk veldig bra. Ble du ikke imponert over hvor flink jeg var?',
    successNn:
      'Dette gjekk veldig bra. Blei du ikkje imponert over kor flink eg var?',
    failureNb: 'Prøv en gang til.',
    failureNn: 'Prøv ein gong til',
    task: [
      x,
      x,
      x,
      x,
      x,
      x,
      x,
      'dot',
      'dot',
      'dot',
      'dot',
      'dot',
      x,
      x,
      x,
      x,
      'dot',
      'dot',
      'dot',
      'dot',
      x,
      x,
      x,
      'dot',
      'dot',
      x,
      x,
      'dot',
      x,
      'dot',
      x,
      c,
      x,
      x,
      v,
      v,
      x,
      'dot',
      'comma',
      'comma',
      'comma',
      'comma',
      m,
      'dot',
      n,
      n,
      'comma',
      'comma',
      'dot',
      b,
      b,
      g,
      t,
      t,
      r,
      f,
      f,
      d,
      e,
      w,
      o,
      o,
      k,
      l,
      l,
      j,
      n,
      'comma',
      'comma',
      'comma',
      'comma',
      'dot',
      'dot',
      'dot',
      d,
      s,
      s,
      a,
      a,
      j,
      u,
      u,
      g,
      æ,
      c,
      'dot',
      r,
      e,
      r,
      t,
      g,
      h,
      h,
      i,
      u,
      y,
      y,
      'comma',
      'comma',
      s,
      o,
      m,
      'som',
      h,
      ø,
      n,
      e,
      'høne',
      r,
      o,
      t,
      'rot',
      'rote',
      d,
      u,
      'du',
      'duk',
      m,
      o,
      t,
      'mot',
      m,
      ø,
      t,
      e,
      'møte',
    ],
    startPosition: [0, -25],
    animation: [
      [70, 40],
      [0, 0],
      [70, 40],
    ],
  },
  {
    time: 180,
    introNb:
      'Oi, så mange puslebiter som ligger her. Jeg er spent på om bitene passer sammen.  De nye tastene er q og p. Du må flytte venstre lillefinger opp til q. Du må flytte høyre lillefinger opp til p. Legg fingrene klare på tastaturet. Da kan vi starte.',
    introNn:
      'Oi, så mange puslebitar som ligg her. Eg er spent på om bitane passar saman. Dei nye tastane er q og p. Du må flytte venstre veslefinger opp til q. Du må flytte høgre veslefinger opp til p. Legg fingrane klare på tastaturet. Då kan vi starte.',
    successNb: 'Ja, vi klarte det!',
    successNn: 'Ja, vi klarte det!',
    failureNb: 'Hm, det er noen biter igjen. Prøv en gang til.',
    failureNn: 'Hm, det er nokre bitar att. Prøv ein gong til!',
    task: [
      q,
      q,
      q,
      q,
      p,
      p,
      p,
      p,
      q,
      q,
      q,
      a,
      a,
      p,
      p,
      ø,
      ø,
      a,
      a,
      s,
      s,
      q,
      q,
      æ,
      p,
      p,
      p,
      f,
      f,
      v,
      v,
      f,
      q,
      k,
      k,
      j,
      j,
      p,
      e,
      v,
      v,
      v,
      i,
      n,
      n,
      u,
      p,
      p,
      c,
      v,
      f,
      t,
      t,
      q,
      q,
      q,
      y,
      b,
      o,
      o,
      p,
      p,
      ø,
      'comma',
      'comma',
      'comma',
      'comma',
      'dot',
      g,
      s,
      s,
      m,
      m,
      o,
      p,
      j,
      r,
      f,
      r,
      e,
      k,
      æ,
      ø,
      p,
      w,
      q,
      f,
      x,
      x,
      l,
      l,
      k,
      k,
      j,
      j,
      'dot',
      'dot',
      'dot',
      f,
      f,
      d,
      d,
      s,
      a,
      q,
      t,
      t,
      j,
      j,
      'dot',
      'dot',
      h,
      h,
      p,
      p,
      j,
      a,
      'ja',
      k,
      l,
      a,
      r,
      'klar',
      f,
      ø,
      r,
      'før',
      'først',
      'alt',
      'par',
      p,
      i,
      l,
      'pil',
      p,
      u,
      s,
      'pus',
    ],
    startPosition: [0, -25],
    animation: [
      [70, 40],
      [0, 0],
      [70, 40],
    ],
  },
  {
    time: 180,
    introNb:
      'Jeg har funnet en hemmelig tunnel. Jeg vil åle meg gjennom den og se hvor den ender. De nye tastene er z, å og bindestrek. Du må flytte venstre lillefinger ned til z. Du må flytte høyre lillefinger opp til å, og ned til bindestrek. Trykk start, så setter vi i gang. ',
    introNn:
      'Eg har funne ein hemmeleg tunnel. Eg vil åle meg gjennom han, og sjå kor han endar. Dei nye tastane er z, å og bindestrek. Du må flytte venstre veslefinger ned til z. Du må flytte høgre veslefinger opp til å, og ned til bindestrek. Trykk start, så set vi i gong. ',
    successNb:
      'Vi klarte å komme oss ut på andre siden. Her var det en nydelig hage',
    successNn:
      'Vi klarte å kome oss ut på andre sida. Her var det ein nydeleg hage.  ',
    failureNb: 'Det var en lang tunnel. Vi begynner på nytt.',
    failureNn: 'Det var ein lang tunnel. Vi startar på nytt.',
    task: [
      å,
      å,
      å,
      å,
      å,
      z,
      z,
      z,
      z,
      z,
      'dash',
      'dash',
      'dash',
      'dash',
      'dash',
      'dash',
      'dash',
      z,
      z,
      z,
      z,
      z,
      å,
      å,
      å,
      å,
      å,
      'dash',
      'dash',
      'dash',
      z,
      z,
      z,
      a,
      a,
      q,
      s,
      s,
      s,
      d,
      d,
      w,
      'dash',
      'dash',
      'dash',
      'dash',
      å,
      å,
      å,
      å,
      æ,
      æ,
      z,
      z,
      f,
      g,
      å,
      å,
      y,
      y,
      o,
      o,
      o,
      z,
      x,
      x,
      'dash',
      'dash',
      å,
      å,
      z,
      å,
      'dash',
      c,
      å,
      p,
      p,
      ø,
      ø,
      'dot',
      'dot',
      l,
      l,
      m,
      'comma',
      'comma',
      o,
      o,
      'dash',
      g,
      r,
      r,
      r,
      e,
      k,
      j,
      ,
      u,
      u,
      i,
      n,
      n,
      n,
      p,
      ø,
      d,
      q,
      q,
      z,
      z,
      h,
      h,
      i,
      u,
      n,
      n,
      'dot',
      'dot',
      b,
      å,
      t,
      'båt',
      h,
      å,
      r,
      'hår',
      'år',
      'åre',
      'tåre',
      s,
      t,
      å,
      'stå',
      'står',
      v,
      v,
      v,
      'vår',
      n,
      n,
      å,
      å,
      l,
      'nål',
      'mål',
    ],
    startPosition: [0, -25],
    animation: [
      [70, 40],
      [0, 0],
      [70, 40],
    ],
  },
  {
    time: 180,
    introNb:
      'Å nei, er klokka blitt så mye? Jeg er sent ute til skolen . Om du kan hjelpe meg med å skrive disse ordene, så kan eg rekke det Husk at du må bruke riktige fingre på de ulike tastene.  Kjenner du f og j?',
    introNn:
      'Å nei, er klokka blitt så mykje? Eg er seint ute til skulen. Om du kan hjelpe meg med å skrive desse orda, så kan eg rekke det. Hugs at du må bruke dei riktige fingrane på dei ulike tastane. Kjenner du f og j?',
    successNb: 'Vi rakk det!',
    successNn: 'Vi rakk det!',
    failureNb: 'Å nei, jeg kom for sent. Prøv igjen!',
    failureNn: 'Å nei, eg kom for seint! Prøv igjen!',
    task: [
      'og',
      'av',
      'for',
      'på',
      'ta',
      'var',
      'tid',
      'vi',
      'vil',
      'den',
      'ut',
      'det',
      'ja',
      'til',
      'er',
      'to',
      'der',
      'inn',
      'nei',
      'har',
      'nye',
      'om',
      'her',
      'som',
      'sin',
      'han',
      'kan',
      'mot',
      'bli',
      'med',
      'må',
      'ha',
      'oss',
      'men',
      'så',
      'alt',
      'skal',
      'dette',
      'går',
      'at',
    ],
    startPosition: [0, -25],
    animation: [
      [70, 40],
      [0, 0],
      [70, 40],
    ],
  },
  {
    time: 180,
    introNb:
      'Jeg elsker å fiske. I dag skal jeg på fisketur. Jeg håper jeg får masse fisk. I hvert fall 10 stykker. Kan du og tastaturet hjelpe meg? Denne gangen er det litt annerledes. Det er tall som kommer opp på skjermen, og du må trykke på de riktige tallene på tastaturet. Tallene står på en rekke over alle bokstavtastene. Du må bruke venstre hånd på 1, 2, 3, 4, 5, og 6. Du må bruke høyre hånd på 7, 8, 9 og 0.  Om du har et stort tastatur, er tallene også på høyre side av tastaturet. Da kan du bruke høyre hånd på alle. Trykk på start når du er klar. ',
    introNn:
      'Eg elskar å fiske.  I dag skal eg på fisketur. Eg håper eg får masse fisk. I alle fall 10 stykk. Kan du og tastaturet hjelpe meg? Denne gongen er det litt annleis. Det er tal som dukkar opp på skjermen, og du må trykke på dei riktige tala på tastaturet. Tala står på ei rekke over alle bokstavtastane. Du må bruke venstre hand på 1, 2, 3, 4, 5, og 6. Du må bruke høgre hand på 7, 8, 9 og 0.  Om du har eit stort tastatur, er tala også på høgre side av tastaturet. Då kan du bruke høgre hand på alle. Trykk på start når du er klar.',
    successNb: 'Helt strålende!',
    successNn: 'Heilt strålande!',
    failureNb: 'Skal vi prøve å fange flere fisk? Start om igjen.',
    failureNn: 'Skal vi prøve å fange fleire fisk? Start om att. ',
    task: [
      3,
      10,
      5,
      7,
      1,
      9,
      2,
      8,
      6,
      7,
      4,
      8,
      5,
      2,
      4,
      9,
      7,
      0,
      1,
      3,
      6,
      10,
      5,
      12,
      15,
      4,
      2,
      19,
      8,
      9,
      5,
      0,
      2,
      3,
      1,
      2,
      3,
      5,
      13,
      11,
      4,
      14,
      1,
      6,
      16,
      8,
      10,
      0,
      20,
      17,
    ],
    startPosition: [0, -25],
    animation: [
      [70, 40],
      [0, 0],
      [70, 40],
    ],
  },
  {
    time: 180,
    introNb:
      'Se, Tastaturid er på toppen av fjellet! Jeg vil opp til henne. For å hjelpe meg opp, må du denne gangen trykke ulike tegn på tastaturet. De fleste tegna finner du på raden sammen med tallene. Her får du en utfordring fordi du må holde nede skifttasten samtidig som du trykker på tasten med rett tegn! Husker du hvordan skifttasten ser ut? Du skal trykke ned skifttasten med venstre lillefinger og tegntasten med høyre hånd.Trykk på start, så begynner vi klatringen.',
    introNn:
      'Sjå, Tastaturid er på toppen av fjellet!  Eg vil opp til ho. For å hjelpe meg opp, må du denne gongen trykke ulike teikn på tastaturet. Dei fleste teikna finn du på rada saman med tala. Her får du ei utfordring fordi du må halde nede skifttasten samstundes som du trykker på tasten med rett teikn! Hugsar du korleis skifttasten ser ut? Du skal trykke ned skifttasten med venstre veslefinger og teikntasten med høgre hand. Trykk på start, så startar vi klatringa.  ',
    successNb: 'Endelig på toppen!',
    successNn: 'Endeleg på toppen!',
    failureNb: 'La oss prøve en gang til.',
    failureNn: 'La oss prøve ein gong til.',
    task: [
      'exclamation',
      'exclamation',
      'question',
      'question',
      'quote',
      'quote',
      'paren-left',
      'paren-right',
      'paren-left',
      'paren-right',
      'exclamation',
      'question',
      'hash',
      'hash',
      'hash',
      'quote',
      'quote',
      'slash',
      'slash',
      'slash',
      'equals',
      'equals',
      'star',
      'star',
      'star',
      'equals',
      'equals',
      'exclamation',
      'question',
      'exclamation',
      'quote',
      'hash',
      'question',
      'paren-left',
      'paren-right',
      'colon',
      'colon',
      'colon',
      'star',
      'star',
      'plus',
      'plus',
      'plus',
      'exclamation',
    ],
    startPosition: [0, -25],
    animation: [
      [70, 40],
      [0, 0],
      [70, 40],
    ],
  },
];

export { tasks };
